### ISSUE TITLE
Cannot get iron-router to install with page 150 commands

### ISSUE THREAD

**Issue by maverick976** [DiscoverMeteor/book#262]
Marks-MacBook-Pro-2:microscope markwhite$ mrt add iron-router

Done installing smart packages

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

iron-router: updating npm dependencies -- connect...
npm WARN using --force I sure hope you know what you are doing.
npm http GET https://registry.npmjs.org/connect/2.9.0
npm http GET https://registry.npmjs.org/connect/2.9.0
npm http 304 https://registry.npmjs.org/connect/2.9.0
npm http GET https://registry.npmjs.org/connect/-/connect-2.9.0.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-2.9.0.tgz
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/uid2/0.0.2
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/multiparty/2.1.8
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/send/-/send-0.1.4.tgz
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm http 304 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/send/-/send-0.1.4.tgz
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/debug/-/debug-0.8.0.tgz
npm http GET https://registry.npmjs.org/methods/-/methods-0.0.1.tgz
npm http 304 https://registry.npmjs.org/multiparty/2.1.8
npm http GET https://registry.npmjs.org/multiparty/-/multiparty-2.1.8.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm http 200 https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/methods/-/methods-0.0.1.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http 200 https://registry.npmjs.org/debug/-/debug-0.8.0.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 304 https://registry.npmjs.org/uid2/0.0.2
npm http GET https://registry.npmjs.org/uid2/-/uid2-0.0.2.tgz
npm http 200 https://registry.npmjs.org/multiparty/-/multiparty-2.1.8.tgz
npm http 200 https://registry.npmjs.org/uid2/-/uid2-0.0.2.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mime
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http GET https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http GET https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/stream-counter/-/stream-counter-0.1.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.26-4.tgz
npm http 200 https://registry.npmjs.org/stream-counter/-/stream-counter-0.1.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.26-4.tgz
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 200 https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http 200 https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm ERR! fetch failed https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm http 200 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm http 200 https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm ERR! fetch failed https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.25-1.tgz
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read](tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write](tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "/Users/markwhite/.meteor/tools/c2a0453c51/bin/node" "/Users/markwhite/.meteor/tools/c2a0453c51/bin/npm" "install" "--force" "connect@2.9.0"
npm ERR! cwd /Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! Error: ENOENT, lstat '/Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn/node_modules/connect/node_modules/send/node_modules/mime/types/mime.types'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "/Users/markwhite/.meteor/tools/c2a0453c51/bin/node" "/Users/markwhite/.meteor/tools/c2a0453c51/bin/npm" "install" "--force" "connect@2.9.0"
npm ERR! cwd /Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path /Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn/node_modules/connect/node_modules/send/node_modules/mime/types/mime.types
npm ERR! fstream_path /Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn/node_modules/connect/node_modules/send/node_modules/mime/types/mime.types
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /Users/markwhite/.meteor/tools/c2a0453c51/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/markwhite/.meteorite/packages/iron-router/EventedMind/iron-router/05f34bc48c4cad9fdaa366c1ddcabe6980232ece/.npm/package-new-f2xkhn/npm-debug.log
npm ERR! not ok code 0

=> Errors while scanning packages:

While building package `iron-router`:
error: couldn't install npm package

**Comment by maverick976** [comment]
could this be a file path length issue? how would you move an entire meteor app to another directory?

**Comment by maverick976** [comment]
simply moving the whole directory to a shorter path allowed iron-router to install. hopefully nothing else will break with the move.
